### ISSUE TITLE
Retain cycle from KSTokenViewDelegate

### ISSUE THREAD

**Issue by gautier-gdx** [khawars/KSTokenView#10]
Hi,

I think you forgot to make the KSTokenview delegate to weak on line 127 in KSTokenView.
This has make a retain cycle and now it's ok, by setting    "weak var delegate: KSTokenViewDelegate?"

Thank for your lib by the way, it's great

**Comment by khawars** [comment]
@gautier-gdx thank you for pointing out. I'll update it probably tomorrow once i reach my computer.

**Comment by khawars** [comment]
@gautier-gdx fixed in latest commit 89c7ce6d5bba73162c74c29e6b9bd5dba450f24f.
You can reopen if there is still any issue.
