### ISSUE TITLE
import data from external VC

### ISSUE THREAD

**Issue by fealonelei** [khawars/KSTokenView#11]
If I have AViewController, and I put KSTokenView on BViewController.  I need segue some data in a dataArray from A to B, when B get it, it should tokenise all data into several token. Unfortunately, I could not figure out how-to.

**Comment by fealonelei** [comment]
here is my code: 

override func viewDidAppear(animated: Bool) {
        super.viewDidAppear(true)
        
        if count(tagsArray) > 0 {
            tokenView.becomeFirstResponder()
            
            for i in 0...(count(tagsArray) - 1) {
                if count(tagsArray) == 1 && tagsArray[0] == "" {
                } else {
                    let token = KSToken(title: tagsArray[i])
                    tokenView.addToken(token)
                }
            }
            tokenView.resignFirstResponder()
        }
    }

However, if I use this, it will show up suddenly! If I put it in other method,such as viewDidLoad() or viewWillAppear(), all titles will NOT tokenise!

**Comment by khawars** [comment]
@fealonelei I guess the KSTokenView is not properly initialized, before tokens are being added.
I'll look into this issue as soon as get to my work computer.

**Comment by fealonelei** [comment]
My KSTokenView on BController is a view on xib, I set its outlet to code. 
then, 
      override func viewDidLoad(){
        tokenView.delegate = self
        tokenView.promptText = "    "
        tokenView.placeholder = "input more tags when click space "
        tokenView.maxTokenLimit = 20 //default is -1 for unlimited number of tokens
        tokenView.style = .Squared
        tokenView.font = UIFont.systemFontOfSize(14)
        ==============
       // if I put code here, when view show up, the tokenView will be empty.
       if count(tagsArray) > 0 {
          tokenView.becomeFirstResponder()

           for i in 0...(count(tagsArray) - 1) {
               if count(tagsArray) == 1 && tagsArray[0] == "" {
               } else {
                let token = KSToken(title: tagsArray[i])
                tokenView.addToken(token)
            }
        }
          tokenView.resignFirstResponder()
      }
      }

**Comment by khawars** [comment]
@fealonelei Issue is fixed in latest commit d7892e2d0f8cc0845a57d3d878ac8fb702fb5911
You can reopen the issue if there is still problem.
