### ISSUE TITLE
Convert this to objective-c

### ISSUE THREAD

**Issue by Horray** [khawars/KSTokenView#12]
This isn't an issue, but this is the only way I have to contact you. My question, can you please translate this to objective-c? I don't know swift, and I want to be able to read this.

**Comment by khawars** [comment]
@Horray you can still use it in your Objective-c project.
See Apple documentation on using Swift code in Objective-c.
There is also an example of using this control in Objective-c project.
There doesn't seem to be any need of translating to Objective-c.

**Comment by Horray** [comment]
Thanks for the reply!

I want to be able to read it, since I can't read swift. I want it for my
own reference.
