### ISSUE TITLE
Cannot build the project using Cocoapods

### ISSUE THREAD

**Issue by aslisabanci** [khawars/KSTokenView#13]
Hi there, 
First of all thank you for open sourcing this component! :beers:

I added KSTokenView using Cocoapods to my project but it doesn't get compiled this way. I think the problem is that KSTokenView class is not visible to my app's target. To make sure of this, I changed the class's access identifier to be public (and made all other necessary changes) and then the project compiled. 

Has anyone else experienced this issue before?

**Comment by khawars** [comment]
@aslisabanci couldn't find such issue. Could you explain in more detail? What necessary changes were made to make it work?

**Comment by aslisabanci** [comment]
Hi @khawars 

Here's how my podfile looks like: 

    platform :ios, '8.0'
    use_frameworks!
    pod 'KSTokenView', '~> 1.2'
    
After running `pod install` , I'm trying to use KSTokenView in one of my classes by importing it as `import KSTokenView`

The project doesn't get compiled because KSTokenView entities are not accessible from my project. This must be because the needed entities aren't specified to be `public`. In Swift, the default access modifier is `internal`. Here's how the access identifiers work, from Apple's documentation:

* *Public* access enables entities to be used within any source file from their defining module, and also in a source file from another module that imports the defining module. You typically use public access when specifying the public interface to a framework.
* *Internal* access enables entities to be used within any source file from their defining module, but not in any source file outside of that module. You typically use internal access when defining an app’s or a framework’s internal structure. 

I think this can be solved by thinking which entities should be open to other modules' access and marking them as public.

**Comment by khawars** [comment]
No need for `import KSTokenView` in Swift based projects.
In Objective-c project, it should be the format `#import "<ProductModuleName>-Swift.h"`
See example project `ObjCExample`. Where it is imported as `#import "ObjCExample-Swift.h"`.

**Comment by aslisabanci** [comment]
My project is Swift based, so I'm importing it as `import KSTokenView`.
This is not the first time I'm importing a project through Cocoapods into my Swift project. If I don't write `import ...`,the project cannot access the entities inside other frameworks and it cannot build the project.

**Comment by gautier-gdx** [comment]
Hi,

Usually you don't need to use any import using Cocoapods for swift project. I might be wrong but you are forcing KSTokenView to be used as a framework, can you try updating your pod without the line 
use_frameworks! in your podfile?

**Comment by aslisabanci** [comment]
Hi @gautier-gdx ,

I tried that too, but here's what Cocoapods gives as an error, when you try to integrate a pod written in Swift, without `use_frameworks!` statement:

    $ pod install
    Analyzing dependencies
    Downloading dependencies
    Installing KSTokenView (1.2.8.3)
    [!] Pods written in Swift can only be integrated as frameworks; this feature is still in beta. Add `use_frameworks!` to your Podfile or target to opt into using it.

So, I need to put this in my Podfile. 

After putting `use_frameworks!` statement, the pod gets installed successfully. But the project doesn't get compiled, as I was saying. By the way, this issue can be reproduced easily by creating a simple project in Swift and integrating KSTokenView into it. 

Thanks for your inputs!

**Comment by quekshuy** [comment]
I'm also facing this issue even with the latest instructions in the README file. Importing KSTokenView doesn't help too. 

XCode 7. Cocoapods 0.38.2., KSTokenView 2.2.0.

**Comment by khawars** [comment]
Issue is fixed in latest commit https://github.com/khawars/KSTokenView/commit/f3969467a56fb1d1d061904bacea0332f49efb9e and latest version of Cocoapods (0.39.0 at time of writing).

**Comment by bayfatih2000** [comment]
I face this problem now. Please help me :(
