### ISSUE TITLE
indentation on first token

### ISSUE THREAD

**Issue by senfi** [khawars/KSTokenView#14]
- build the Examples/SwiftExample/SwiftExample.xcodeproj project
- add a few token to get into the second line of tokens
There is a gap between the first token of the first line and the other first tokens of the other lines (see the added red line in attached screenshot)

Is this gap intented or a bug?
![indent](https://cloud.githubusercontent.com/assets/806859/8673660/b40a89c8-2a38-11e5-9f1b-317f88fb25d9.png)

(Build with Xcode 6.4 on iPhone 6 iOS 8.4 Simulator)

**Comment by khawars** [comment]
@senfi issue if fixed in latest commit c8883847f87ae0dc3c3d22736d2827d653145e6c. You can re-open the issue if there is still any issue.

**Comment by senfi** [comment]
Works great. Thanks!
