### ISSUE TITLE
Is it possible to use a UITextField with your framework ?

### ISSUE THREAD

**Issue by luvmiracles** [khawars/KSTokenView#15]
Sorry I'm not sure if I fully understand the usage of your code. I know am able to create a view as KSTokenView but is it possible to directly use a uitextfield instead as KSTokenField ? 

Thanks

**Comment by khawars** [comment]
`KSTokenField` is inherited from `UITextField`. If you want to directly access it just make it public in `KSTokenView` class.

**Comment by luvmiracles** [comment]
Thank you for your help .
