### ISSUE TITLE
Autolayout: grow KSTokenView to include UITableView

### ISSUE THREAD

**Issue by senfi** [khawars/KSTokenView#16]
When using Autolayout, is it possible to grow the height-constraint of the KSTokenView to include the table view and not just the tokens? I made an example to make clear what i mean: 4f289e3c4e56bcb56e09933151e3414506a0ff9d 

The green UIView is below the KSTokenView and they are connected via a a "vertical space"-constraint. The green view moves down, when tokens are added, but it does not move below the tableview. Is there a way to include an option to do this or can you point me to the heigth-calculation?
![vertical space constraint pushes green view down](https://cloud.githubusercontent.com/assets/806859/9225175/01b3fd7c-4108-11e5-99ab-c26673134534.png)

![KSTokenView-height does not include tableView](https://cloud.githubusercontent.com/assets/806859/9225196/3416e950-4108-11e5-811e-bacae608cea9.png)

**Comment by khawars** [comment]
@senfi, currently there is no way to link search results tableview with any other external view element. You have to manually calculate the search result position and update external view. Here is a rough example

   func tokenView(tokenView: KSTokenView, didChangeFrame frame: CGRect) {
      var frame = myView.frame
      frame.origin.y = tokenView.frame.maxY+tokenView.searchResultSize.height
      myView.frame = frame
   }
   
After the search result is hidden, you can re-locate the view.
   func tokenViewDidHideSearchResults(tokenView: KSTokenView) {
      var frame = myView.frame
      frame.origin.y = 150 // or whatever was the initial position
      myView.frame = frame
   }

Two delegates, tokenViewDidHideSearchResults and tokenViewDidShowSearchResults are added in latest commit today 03e7507e3d7dcf7faa068501815b46f034884d5e.

**Comment by senfi** [comment]
Yeah, great idea. Thank you for your support! This should work.
