### ISSUE TITLE
Trying to Use KSTokenView with Cocoapods, XCode 7, and Swift 2

### ISSUE THREAD

**Issue by frodgers1207** [khawars/KSTokenView#19]
I'm trying to use your project in my swift 2, xcode 7 project. I installed it in Cocoapods with

    platform :ios, '8.0'
    use_frameworks!
    pod 'KSTokenView'

it installed KSTokenView 1.3.0. The 1.3.0 version has almost 200 errors right now in my workspace. When I look in the podspec file it says that the s.version is 2.0.0. When I have tried to use that version and install `pod 'KSTokenView', '~> 2.0.0'` I get an error during the pod install. Do you know what could be causing the error with the 2.0.0 version? I would really like to use this framework because it would really help me with my project.

**Comment by khawars** [comment]
@frodgers1207 I'll fix this issue on Monday. However you can still use it by manually adding in your code.

**Comment by frodgers1207** [comment]
Okay thanks, I'll try again manually but I was getting a Segmentation fault: 11 when I tried manually.

**Comment by khawars** [comment]
Yes, you are right. I still need to update it for Xcode 7. Unfortunately, I have changed my Mac machine and setting up development environment. Will look into these issue on Monday.

**Comment by frodgers1207** [comment]
Okay great, thank you.

**Comment by mineono** [comment]
The optional delegates <pre>optional func tokenView(tokenView: KSTokenView, willChangeFrame rectDict: CGRect)</pre>and<pre>optional func tokenView(tokenView: KSTokenView, didChangeFrame rectDict: CGRect)</pre> are the problem here.<br />Quick workarround:<br/>Change CGRect to e.g. NSDictionary and map the data. Now the compiler knows what to do.

**Comment by khawars** [comment]
Updated code with Xcode 7.0/Swift 2.0 in latest commit 9cbf7056d64d21381b74da6760c56a32a70103b0. Will do few modifications in a day or two.
You can re-open issue if it exists.
