### ISSUE TITLE
token.title string equality not working

### ISSUE THREAD

**Issue by daemonDevarshi** [khawars/KSTokenView#21]
I am trying to implement below delegate method:

```
func tokenView(tokenView: KSTokenView, shouldAddToken token: KSToken) -> Bool {
        var shouldAddToken = true
        
        if token.title == "f" {
            shouldAddToken = false
        }
        
        print("~~ tokenTitle : \(token.title) , shouldAddToken : \(shouldAddToken)")
        
        return shouldAddToken
    }
```

Problem is - though I have entered 'f' in tokenView shouldAddToken is coming to be nil, i.e. equality check is failing :(

Here is output of print statement in console:

`~~ tokenTitle : ​f , shouldAddToken : true`

Please suggest

**Comment by khawars** [comment]
Issue is fixed in latest commit https://github.com/khawars/KSTokenView/commit/f3969467a56fb1d1d061904bacea0332f49efb9e

Check example ```AutolayoutExample```.
