### ISSUE TITLE
tokenView.isFirstResponder() does not work properly

### ISSUE THREAD

**Issue by Jackson0111** [khawars/KSTokenView#22]
Everything else is great, thanks for your work! In shouldAddToken function, tokenView.isFirstResponder does not work properly. When it is actually first responder, .isFirstResponder gives false value.

**Comment by Jackson0111** [comment]
Never mind, I made a mistake.

**Comment by Jackson0111** [comment]
Can you use tokenView.isFirstResponder()?

**Comment by khawars** [comment]
@Jackson0111 issue is fixed in latest commit https://github.com/khawars/KSTokenView/commit/edb5d2034c6a02584fa4f6c41ea203e6a4826aa9
