### ISSUE TITLE
Autoresize UITableViewCell with TokenView

### ISSUE THREAD

**Issue by eshwartm** [khawars/KSTokenView#24]
I have added `KSTokenView` as a subview of `UITableViewCell`. (Like in the behavior of `UITextView`)
But it won't resize the table view cell the way `UITextView` does. 

Any solution for this?

**Comment by khawars** [comment]
Could you please post your example code?  I'll look into it soon.

**Comment by eshwarramesh** [comment]
Ok. Here what's I did. 

- Construct a UITableViewCell xib with an outlet for KSTokenView.  
- By autolayout, anchor the token view to all sides (top, bottom, left, right) of the content view. 
- Register this xib with the table view by code.
- In the custom tableviewcell class, add the listener delegate `tokenView(tokenView: KSTokenView, didChangeFrameWithX: CGFloat, y: CGFloat, width: CGFloat, height: CGFloat)`
- Now start typing into the token view cell. 
- As we type, the frame of the token view changes in some way, when we go to new line or something. 
- The `didChangeFrame` method is fired. 
- Get the reference of tableview from the cell in the method. Do `beginUpdates` and `endUpdates`. 

Result is that the frame of the cell and tableview does not change. Only the token view expands.

**Comment by eshwartm** [comment]
Ok. Here what's I did.

Construct a UITableViewCell xib with an outlet for KSTokenView.
By autolayout, anchor the token view to all sides (top, bottom, left, right) of the content view.
Register this xib with the table view by code.
In the custom tableviewcell class, add the listener delegate tokenView(tokenView: KSTokenView, didChangeFrameWithX: CGFloat, y: CGFloat, width: CGFloat, height: CGFloat)
Now start typing into the token view cell.
As we type, the frame of the token view changes in some way, when we go to new line or something.
The didChangeFrame method is fired.
Get the reference of tableview from the cell in the method. Do beginUpdates and endUpdates.
Result is that the frame of the cell and tableview does not change. Only the token view expands.

Also, it seems like the search results table view is not hiding when CGSizeZero is given for searchResultSize. I don't know if I am doing something wrong. But I want to be able to hide the search results table view.

**Comment by khawars** [comment]
Better to ask this problem on Stackoverflow

**Comment by Sianay** [comment]
Have you find a solution for that @eshwartm ?

**Comment by eshwartm** [comment]
@Sianay I kind of found the solution. I'll update it soon.

**Comment by hemaks777** [comment]
Hi, 

How can we resize the UITableViewCell based on tokenView height? Kindly provide a solution.
