### ISSUE TITLE
Please add Right to Left support

### ISSUE THREAD

**Issue by AmeerTgh** [khawars/KSTokenView#25]
i want to use in right to left, please help me.

thanks.

**Comment by khawars** [comment]
This feature is currently not supported. I'll definitely add this soon

**Comment by AmeerTgh** [comment]
Thank you so much :)

**Comment by khawars** [comment]
@AmeerTgh I am getting enough time to add this feature. Better if you could add this and submit a pull request. I am not sure if I would work on it in near future.
