### ISSUE TITLE
Custom Font crash

### ISSUE THREAD

**Issue by eshwartm** [khawars/KSTokenView#26]
Giving a custom font like `UIFont("Helvetica-Neue", size:14)` crashes at private function `_updateTokenField`. Could you please look into this?

**Comment by khawars** [comment]
Make sure ```font``` is not nil. Try this to check if compiler passes first line and you have a valid font. Then assign it to tokenView.
```let font = UIFont(name: "Helvetica-Neue", size:14)!```
```tokenView.font = font```

**Comment by eshwartm** [comment]
Actually, I checked it the way you are saying.

    private func _updateTokenField() {
          _tokenField.parentView = self          // crashes here
    }

**Comment by eshwartm** [comment]
Correction on the font name, it is `HelveticaNeue`. But it still crashes.

**Comment by eshwartm** [comment]
So I have made 2 changes in the code. 

1.
In file `KSToken.swift`

    var font = UIFont.systemFontOfSize(14)
    var tokenField: KSTokenField? {
         return superview?.superview as? KSTokenField
    }

The `superview` returned from here was the `scroll view` inside the `KSTokenField` and not the `KSTokenField` itself. I changed it to `superview?.superview`.

2.
In `_commonSetup()`, I added `_tokenField.font = font` and updated the `_updateTokenField()` method to

    private func _updateTokenField() {
          if _tokenField == nil {
             _commonSetup()
          }
          _tokenField.parentView = self
    }

Because the font was not being taken by the `_commonSetup()` method, and also the custom font was getting applied to a `tokenField` that did not exist initially. That's why it was crashing in `_tokenField.parentView = self`.

**Comment by eshwartm** [comment]
Please check if these changes are necessary.

**Comment by khawars** [comment]
Please check example code for custom fonts https://github.com/khawars/KSTokenView/tree/master/Examples/AutolayoutExample

It seems working fine for me.

If issue still exists, please re-open the issue.

**Comment by alizainprasla** [comment]
@khawars Provide link is not working.

**Comment by khawars** [comment]
That example was removed from latest commits. You may download older version 2.4.0 with Swift 2 from following link.
https://github.com/khawars/KSTokenView/archive/2.4.0.zip
And see ```AutolayoutExample``` project.
