### ISSUE TITLE
check if token has some prefix

### ISSUE THREAD

**Issue by d4r1091** [khawars/KSTokenView#27]
Hi,
I've a problem when added this beautiful library into my Obj-c project.
When checking if [aToken.title hasPrefix:@"somePrefix"], it enters anyway even if there is no prefix.
I read something about "optional string" using swift and after placed a breakpoint and check with lldb, I found that check returns <nil>.
How can i solve this?
thanks a lot!
Dario

**Comment by d4r1091** [comment]
Nothing?
BTW many compliments for your app! It is a very time wasted solution ;) thanks again

**Comment by khawars** [comment]
Issue is not found. I am trying with following code and its working as expected.
```
- (void)tokenView:(KSTokenView *)tokenView didAddToken:(KSToken *)token {
   
   if ([token.title hasPrefix:@"aa"]) {
      NSLog(@"IF");
   }
}
```

 Please provide more detail on it. You can re-open issue if you think it exists.

**Comment by d4r1091** [comment]
ok thanks a million! In these days I'll test it and check hoping all is well done ;) thanks
