### ISSUE TITLE
how do I change the color (background/text) of the tokens

### ISSUE THREAD

**Issue by boazin** [khawars/KSTokenView#3]
Once again - awesome control!

(I'm using an Obj-C project)
I see I have a `@interface KSToken : UIControl`
but I don't know how to access it. The object I actually have in hand is `KSTokenView` and it has no such interface

Thanks

**Comment by khawars** [comment]
@boazin ```KSTokenView``` is container class that contains all ```KSToken``` objects. You can access ```KSToken``` object reference, when you create it yourself and add it in ```KSTokenView``` container.
In Objective-C you can create ```KSToken``` using following constructors.
```
- (instancetype)initWithCoder:(NSCoder *)aDecoder;
- (instancetype)initWithTitle:(NSString *)title;
- (instancetype)initWithTitle:(NSString *)title object:(id)object;
- (instancetype)initWithTitle:(NSString *)title object:(id)object font:(UIFont *)font
```
**Example:**
```KSToken *token = [[KSToken alloc] initWithTitle:"New Token" object:MY_CUSTOM_OBJECT_OR_NIL];```
You can also access an ```Array``` of all already added ```KSToken``` objects, using ```tokens``` property of ```KSTokenView```.
```NSArray *array = self.tokenView.tokens;```

**Comment by boazin** [comment]
Yeah... but the `addToken(token)` is done internally (in `didSelectRowAtIndexPath` for example)
So I need some kind of an interface to tell `KSTokenView` to init them at a specific color

**Comment by khawars** [comment]
```addToken(token)``` is publicly available ```KSTokenView``` class. You can do like:
```[self.tokenView addToken:token];```

**Comment by boazin** [comment]
I see that, but I want the internal calls (called when the user types) to have a different color - so I need to set the color "in advance". You see my point?

**Comment by khawars** [comment]
@boazin I couldn't understand. Can you explain in more detail what you are trying to accomplish? FYI, you can change the color of ```KSToken```, before or even after you add it in ```KSTokenView```.
Check the example project ```ProgrammaticallyExample```

**Comment by boazin** [comment]
OK. I got the confusion. Take `ProgrammaticallyExample` as an example. When you click add token - it is my own code - cool.
But what I'm looking for - is when I click the control, type something and click Done (which tokenizes the input text) - to be gray instead of blue, and black text instead of white etc.
It would have been nice to control it somehow.

I think it requires a re-design...

**Comment by khawars** [comment]
@boazin Got your point. I have updated the ```ProgrammaticallyExample``` example and ```KSTokenView``` class. Check the latest commit: https://github.com/khawars/KSTokenView/commit/153ad7bd64744091b965d7fb115808db4155ed19
