### ISSUE TITLE
I have problems with AutoLayout

### ISSUE THREAD

**Issue by jchesne** [khawars/KSTokenView#4]
Hi,
I don't know why but when i set AutoLayout constraints left:0 top:0 right:0 height:30 for KSTokenView, the KSTokenView is larger than the superView : 

![capture d ecran 2015-03-26 a 17 20 46](https://cloud.githubusercontent.com/assets/1859737/6850965/809cf330-d3dc-11e4-9c93-58f330865a4b.png)

Is there a bug or my fault ?

**Comment by khawars** [comment]
@jchesne This seems to be a bug. I am looking into it. Will update ASAP.

**Comment by jchesne** [comment]
Great ! Thanks in advance !

**Comment by khawars** [comment]
@jchesne Autolayout issue is fixed in latest commit 302dd4bd3e69393764cd58cec1ddb685c041371f. You can re-open if there is still any issue.

**Comment by krzyzanowskim** [comment]
I have problem that view is changing the height when adding first token. Not sure what I'm doing wrong

![2016-03-19 17_07_39](https://cloud.githubusercontent.com/assets/758033/13899710/1ef149fe-edf5-11e5-9901-364d59b9b71a.gif)

![screen shot 2016-03-19 at 17 03 55](https://cloud.githubusercontent.com/assets/758033/13899683/9583ab94-edf4-11e5-8239-a37302e585fd.png)
