### ISSUE TITLE
Auto Layout issue in UITableViewCell

### ISSUE THREAD

**Issue by sdtaheri** [khawars/KSTokenView#44]
Hi,

I've worked on this issue a lot myself and searched the whole StackOverFlow. Unfortunately I had no luck fixing it so I decided to ask the author @khawars . 
I'm using self sizing cells using Auto Layout targeting iOS 8 and above. Since this control overrides Intrinsic Content Size, I believe it should not have any problems with this. 
I've set up a custom UITableViewCell in Storyboard consisting a UiLabel pinned to top, leading and trailing edges and a KSTokenView pinned to the label, leading and trailing and bottom edges. Practically these constraints are enough if both elements could size themselves based on their content. For example I have another custom cell in the same UITableView replacing the Token View with another UILabel and it just works fine. 
I then added an outlet to this Token View and when it got set, I set the desired properties for this control and added some tokens. 
Here comes the problem: I launch the app and the table view comes on screen. Unfortunately the height has not be set automatically by auto layout yet and it will not until I scroll past this cell and come back to it. In another words, it only makes itself correct in size in the second pass of layout. I've already tried multiple combinations of setNeedsLayout and layoutIfNeeded on the cell, cell.contentView and the TokenView without any luck.
Do you know what is causing the problem?

Thanks in advance.

**Comment by bot2600** [comment]
I've been poking around at this code a bit lately and while I don't have a direct answer for you (I didn't look closely at the autolayout example) from what I saw the easiest way to handle this would be to make the cell the delegate of the tokenview which has a shouldchangeheight or something like that which you could then use to push out the height constraint on your cell. It isn't the normal auto resize but it should get you what you seem to be looking for.

I know you posted a month ago and probably don't need it anymore, but I thought I would throw it out there, and Khawar may very well have a better answer anyhow :)

**Comment by khawars** [comment]
@sdtaheri Apology for such a late reply. Do you still have the issue. If yes, I appreciate if you could provide some example code of how you are using this control in your project. Replicating the project environment on my end is very time consuming and I wouldn't be able to do that.
I am closing the issue now, you may reopen, if issue is still there and you can provide sample code.
