### ISSUE TITLE
KSTokenView resign first responder issue

### ISSUE THREAD

**Issue by anthonycastelli** [khawars/KSTokenView#46]
When resigning the first responder, text in the cell doesn't become tokenized. If I type in a word and then tap in another textField or textView, that text isn't tokenized. 

I've tried setting `removesTokensOnEndEditing` to false but it did nothing

**Comment by khawars** [comment]
@anthonycastelli text is tokenized only after user press "Done" button in keyboard or any of character specified in ```tokenizingCharacters``` array.
