### ISSUE TITLE
[Improvement] Split text with space

### ISSUE THREAD

**Issue by jchesne** [khawars/KSTokenView#5]
Is it possible to tranform a text like this : Hello how are you. Into splited token ?
result : Hello,how,are,you (like the Pinterest app for iPad)

**Comment by khawars** [comment]
@jchesne I am not sure what is the functionality of Pinterest app. I will check that on Monday.
For now I have updated code. Check the latest commit https://github.com/khawars/KSTokenView/commit/f9439e1c0ea672aa016d5df06328c646884e4a6f

Whenever some characters like " " or "," are pressed, token is created with previous text. There is property ```tokenizingCharacters```. You can add/remove any character in the Array like this ```tokenizingCharacters = [" ", ","]```

**Comment by jchesne** [comment]
@khawars Thanks a lot it's working !
But i think this line is not working properly ; if (contains(tokenizingCharacters, string) && olderText != KSTextEmpty) 
If you write 2 space, you create one empty token, maybe the olderText != KSTextEmpty is not correct.

**Comment by khawars** [comment]
FIXED. See latest commit https://github.com/khawars/KSTokenView/commit/f3d104da7c27f1b595523ea9db15eabc4b0b43d5
That was actually not empty token. That contained space characters.

**Comment by jchesne** [comment]
You are fucking awesome ! Big thanks !
