### ISSUE TITLE
Placeholder and input text are not even

### ISSUE THREAD

**Issue by mmilakovic** [khawars/KSTokenView#50]
Hey,

I have problem because placeholder and input are not even (see attachment). Is there possibility to make them even? Maybe after accepting PR#48 and exposing paddingY property as public I could solve this problem. 
![image](https://cloud.githubusercontent.com/assets/6659472/17000132/6ce87c22-4ec1-11e6-9622-e4485ea21323.JPG)

Thanks in advance,

**Comment by khawars** [comment]
This issue is fixed in latest commit.
