### ISSUE TITLE
unexpectedly found nil while unwrapping an optional value (using in table view cell)

### ISSUE THREAD

**Issue by urschaitanya** [khawars/KSTokenView#52]
private func _initPlaceholderLabel() {
      let xPos = _marginX!
      if (_placeholderLabel == nil) {
         _placeholderLabel = UILabel(frame: CGRect(x: xPos, y: leftView!.frame.origin.y, width: _selfFrame!.width - xPos - _leftViewRect().size.width, height: _leftViewRect().size.height))
         _placeholderLabel?.textColor = placeHolderColor
         _placeholderLabel?.font = _font
         _scrollView.addSubview(_placeholderLabel!)
      } else {
         _placeholderLabel?.frame.origin.x = xPos
      }
   }

**Comment by khawars** [comment]
@urschaitanya I would request to provide more information or sample project of issue. If possible please submit PR.

**Comment by reshadf** [comment]
I had the same issue. After some debugging, I have created a pull request to fix it. However, I don't think the library is maintained very well any longer. @urschaitanya I am not sure if you are still using it but the pending Merge request should fix this issue :) 

/cc @khawars
