### ISSUE TITLE
Dropdown table view is under the main UI elements

### ISSUE THREAD

**Issue by codinggenie** [khawars/KSTokenView#53]
If I have a button just below the KSTokenView, the dropdown table for search results is behind the button. So the first row is not visible.
<img width="367" alt="screen shot 2016-09-05 at 03 10 27" src="https://cloud.githubusercontent.com/assets/13944202/18234069/57b10d64-7316-11e6-9eca-460500eb6a95.png">

**Comment by khawars** [comment]
In interface build, make sure to add button to bottom in hiercharchy. See attached screenshot.
![Uploading Screen Shot 2016-09-13 at 11.39.05 PM.png…]()
