### ISSUE TITLE
iOS10 infinite loop when dismissing list

### ISSUE THREAD

**Issue by netgfx** [khawars/KSTokenView#55]
There is a part where the loop never ends on iOS10, swift 2.2

```
for index in 0 ... self.constraints.count - 1 {
						let constraint: NSLayoutConstraint = self.constraints[index] as NSLayoutConstraint

						if (constraint.firstItem as! NSObject == self && constraint.firstAttribute == .Height) {
							constraint.constant = height
						}
					}
```
on KSTokenView

any ideas?

**Comment by netgfx** [comment]
Upon further investigation the problem is here:
```
if (frame.size.height != tokensMaxY) {
				tokenFieldDelegate?.tokenFieldShouldChangeHeight(tokensMaxY)
			}
```
because at one point the `frame.size.height` is 31.0 and `tokensMaxY` is 31.065463 !!!

**Comment by netgfx** [comment]
This seems to solve the problem:
```
if (frame.size.height != round(tokensMaxY)) {
   tokenFieldDelegate?.tokenFieldShouldChangeHeight(tokensMaxY)
}
```

**Comment by netgfx** [comment]
Added PR for this: https://github.com/khawars/KSTokenView/pull/56

**Comment by khawars** [comment]
@netgfx Please try to use latest commit with stable version of Xcode 8.0. I actually couldn't replicate this issue. If you still face this issue, please reopen.
