### ISSUE TITLE
can't select items listed in autocomplete list while the view is inside UIStackView

### ISSUE THREAD

**Issue by Lithium-HD** [khawars/KSTokenView#58]
Hi.
I'm developing an app using swift 2 and some where in my project I need to use your KSTokenView.
TokenView works great when it is not inside a UIStackView. as soon as I put it inside UIStackView (for resizing the app on rotation or bigger screens)  I can't select any items listed in the box in bottom of it. why is that?

**Comment by khawars** [comment]
It should work. Please example project "StackViewExample". You may debug the view hierarchy, to confirm if there isn't any view on top of it.

**Comment by Lithium-HD** [comment]
here's my test project. I've put the KSTokenView inside stackView without any extra views on the screen. it stops working correctly after I did that. take a look.
[TestProject.zip](https://github.com/khawars/KSTokenView/files/484221/TestProject.zip)

**Comment by khawars** [comment]
Try to use latest code from branch ```develop/swift2.3```
