### ISSUE TITLE
HorizontalExample bug

### ISSUE THREAD

**Issue by jchesne** [khawars/KSTokenView#6]
Try to write this token : Hello how are you test
You will see that the test word is over the 'you' token until you press Done button.

And again, thanks for your effort !

**Comment by khawars** [comment]
Thanks @jchesne to point out this. I will look into this on Monday.

**Comment by khawars** [comment]
@jchesne Fixed in latest commit 7df6859c72fa3dedfe27ce56994b81e425b51946
If there is still issue, you can reopen it.

**Comment by jchesne** [comment]
Fixed, big thanks !
