### ISSUE TITLE
autolayout on view 

### ISSUE THREAD

**Issue by devlixz** [khawars/KSTokenView#60]
i follow example horizontal KSTokenView, if i change custom autolayout constraint, it not working well.. I need some advice,how the use of constraint on KSTokenView. thanks. Great project!

![screen shot 2016-09-21 at 11 28 38 pm](https://cloud.githubusercontent.com/assets/22350941/18719964/dca7943a-8053-11e6-8f40-6d9af37580fd.png)

i create KSToken in the middle between textfield like this
![screen shot 2016-09-21 at 11 34 41 pm](https://cloud.githubusercontent.com/assets/22350941/18720040/2c169e94-8054-11e6-804c-9c43a821f80e.png)

and i add some autolayout contraint, then become

![screen shot 2016-09-21 at 11 32 17 pm](https://cloud.githubusercontent.com/assets/22350941/18720054/3fe2a080-8054-11e6-9c48-4b7725b2a982.png)

**Comment by khawars** [comment]
Are you using stable version of Xcode 8?

**Comment by devlixz** [comment]
yes sir, im using stable Version Xcode 8

**Comment by khawars** [comment]
@devlixz I am not able to replicate issue on my end. Please try to use latest source code. If still having issue, please send me sample project.

![simulator screen shot 22-sep-2016 1 17 23 pm](https://cloud.githubusercontent.com/assets/10417908/18741142/f3331e5e-80c6-11e6-8f3c-5e62c125c7d3.png)
![simulator screen shot 22-sep-2016 1 17 31 pm](https://cloud.githubusercontent.com/assets/10417908/18741143/f338287c-80c6-11e6-9aa2-a3dd960c867f.png)

**Comment by devlixz** [comment]
can please check and fix this sir... 

![screen shot 2016-09-23 at 2 34 15 pm](https://cloud.githubusercontent.com/assets/22350941/18777888/c16ee77e-819b-11e6-88f6-f391b32e0846.png)



This example Project 
[KSTokenView-develop-swift2-2.3.zip](https://github.com/khawars/KSTokenView/files/489109/KSTokenView-develop-swift2-2.3.zip)
