### ISSUE TITLE
add version 2.5 and 3.0 to CocoaPods Specs Repo

### ISSUE THREAD

**Issue by alexkaessner** [khawars/KSTokenView#62]
I just noticed that both version [2.5.0](https://github.com/khawars/KSTokenView/releases/tag/2.5.0) and [3.0.0](https://github.com/khawars/KSTokenView/releases/tag/3.0.0) aren't on the official CocoaPods Specs Repo: https://github.com/CocoaPods/Specs/tree/master/Specs/KSTokenView

**Comment by MortenGregersen** [comment]
Still needed...

**Comment by khawars** [comment]
3.0.1 is added on Cocoapods.

**Comment by alexkaessner** [comment]
But now there's only v2.4.1 and next 3.1.0 here: https://github.com/CocoaPods/Specs/tree/master/Specs/0/7/9/KSTokenView

Would be nice to also have v2.5.0 if you're still using Swift 2

**Comment by khawars** [comment]
@alexkaessner Done. Thank you to point out.

**Comment by alexkaessner** [comment]
@khawars Thanks a lot!! 👌
