### ISSUE TITLE
Problem with StackView example

### ISSUE THREAD

**Issue by ggilley** [khawars/KSTokenView#63]
When I try in my app (and I verified with your stack view example), the vertical size is wrong. Any idea what is going wrong?

<img width="375" alt="screen shot 2016-10-09 at 12 09 26 pm" src="https://cloud.githubusercontent.com/assets/3057017/19222977/5b725264-8e19-11e6-86f6-b819778666d4.png">

**Comment by khawars** [comment]
Fixed. Please review the latest commit, if you still find this issue then reopen it.
