### ISSUE TITLE
KSTokenView description text gets blank while start scrolling

### ISSUE THREAD

**Issue by kamil3** [khawars/KSTokenView#64]
It looks like a bug. Steps to reproduce: 
1. Add a proper number of tokens to make the scroll active. 
2. Hide keyboard to show description text or a list of tokens separated by commas. 
3. Start scrolling vertically/horizontally (depending on a direction setup) in KSTokenView (not clicking, just start scrolling) - as a result, the KSTokenView element gets completely empty.

I hope that I made myself clear :-).

**Comment by khawars** [comment]
Fixed. Please review the latest commit, if you still find this issue then reopen it.
