### ISSUE TITLE
All texts are not aligned to their baselines

### ISSUE THREAD

**Issue by jendaz** [khawars/KSTokenView#68]
If I set `promptText` and write something the UITextField is not well aligned. Then If I add one token the text of the token is worse aligned and UITextField is also on a different level. I tried that with custom font.

**Comment by khawars** [comment]
Can you please provide some screenshot?

**Comment by jendaz** [comment]
Sure. I'm using font: ProximaNovaSoft-Regular 15.0
And as you can see there is error -0.5pt for token - textField
And +1pt error for prompt if there are some tokens already.
The screenshot is for @2x scale.


![baselines](https://cloud.githubusercontent.com/assets/8435946/19854367/e9d07c32-9f6e-11e6-8e35-a2dbb2663672.png)
_The green line is the right baseline for the text_


![blended](https://cloud.githubusercontent.com/assets/8435946/19854368/e9d45bfe-9f6e-11e6-9fe8-324d6fe6c15e.png)
_This is three states blended over each other_

**Comment by jendaz** [comment]
Sorry I've sent you my little bit "corrected" version. If I turn that correction off it looks like this:

![tokens](https://cloud.githubusercontent.com/assets/8435946/19883851/c731ae14-a016-11e6-88c9-a2dda81367ca.png)

The textfield position is different when there is a token.

**Comment by khawars** [comment]
Token alignment is independent of prompt text. It actually depends total height of Token View. However, promptText and descriptionText are aligned now. Please review latest commit, if you still find issue reopen it.
