### ISSUE TITLE
Token add start from mid when on full view

### ISSUE THREAD

**Issue by asher636** [khawars/KSTokenView#69]
I added KSTokenView on my UIView which is of screen size i.e in terms of width and height. When ever I click on it, first tag starts from middle. How to fix this? 
I have attached the screenshot. 

Thanks.

<img width="301" alt="screen shot 2016-11-10 at 12 21 34 am" src="https://cloud.githubusercontent.com/assets/17403246/20151354/ac409f04-a6db-11e6-8a81-cc1f48d3fa51.png">

**Comment by khawars** [comment]
Fixed. Please review the latest commit, if you still find this issue then reopen it.

**Comment by asher636** [comment]
okay

Thanks & Regards,
[image: https://wizdevelopers.com]
