### ISSUE TITLE
autocomplete TableView hides KSTokenField when adding tokens programatically

### ISSUE THREAD

**Issue by boazin** [khawars/KSTokenView#7]
When adding programatically - the autocomplete TableView is in a fixed y of 30 - it ignores the tokens that were inserted (the caret is in the correct location)

I tried to debug it a bit and got lost.

Steps to recreate:
1. ProgramaticallyExample project.
2. Do some add "Add Token Programmatically" clicks until you pass the first line of tokens.
3. Try and add a token by typing

Thanks.

**Comment by khawars** [comment]
Thanks @boazin to point out. Fixed in latest commit https://github.com/khawars/KSTokenView/commit/e992d523b92a5d80e4d5a19e201ea6693c6ebfa3
