### ISSUE TITLE
Swift3: Click not working at the center of cells

### ISSUE THREAD

**Issue by codinggenie** [khawars/KSTokenView#70]
Click on the cells not working properly on all cells. It works properly only on the 2nd row.
Order rows click works only in the space between the previous row cell and the text of current cell.
What would be the issue ?

For the image below, click on "C" works fine, not other row cells.
<img width="370" alt="screenshot 2016-11-15 at 00 39 48" src="https://cloud.githubusercontent.com/assets/13944202/20278994/d1e0403a-aacc-11e6-841e-58ea59077fd5.png">

This is the image I got from debugging the view hierarchy for the table view cell.
<img width="483" alt="screenshot 2016-11-15 at 00 43 44" src="https://cloud.githubusercontent.com/assets/13944202/20278996/d3ba9824-aacc-11e6-98d6-3c49a7b166dc.png">

What can I do to correct the click behavior ?

**Comment by khawars** [comment]
Unfortunately, I am not able to replicate this issue on my end. It is working fine. Please review the latest commit, if you still find this issue then reopen it.
