### ISSUE TITLE
Text is not displaying while typing in Objective-c ViewController

### ISSUE THREAD

**Issue by ajay2c9** [khawars/KSTokenView#71]
how to display the typing text displaying in the KSTokenView in objective-c. I implemented the tableview and search bar in the view controller in objective-c . Now I want to implement the KSTokenView instead of UISearchBar. 
Please give suggestions to implement this in Objective-c
Thank you

**Comment by khawars** [comment]
@ajay2c9 Could you please clarify your question?

**Comment by ajay2c9** [comment]
Hi,
Sorry for the late response.

I am using KSTokenView. I loaded the table view after entering to the viewController without searching . After I selected the 3 users . The usernames are not displaying in the Tokenfield . After selecting the KSTokenView the names are displaying. 

I am using objective-c Code.
Please give suggestions to overcome this problem.

Thank you

**Comment by khawars** [comment]
Can you please provide screenshot?

**Comment by ajay2c9** [comment]
![screen shot 2016-12-21 at 10 06 26 am](https://cloud.githubusercontent.com/assets/9112899/21377557/7b6f7148-c765-11e6-9497-579f51996670.png)

After selecting the users it is displaying like above image.

![screen shot 2016-12-21 at 10 07 04 am](https://cloud.githubusercontent.com/assets/9112899/21377580/9d5ecc18-c765-11e6-98aa-8839b8caa31f.png)

After selecting the TokenView the keyboard is appearing and names are displaying those who are selected before.

**Comment by khawars** [comment]
@ajay2c9 are you using latest version of KSTokenView with latest version of Xcode? This is strange, can you provide sample project of this screen, so that I can inspect accordingly?

**Comment by ajay2c9** [comment]
Hi khawars,
I am using the latest version of KSTokenView in xcode 8.0. I few changes in objective-c files plz check below. 
1. In Viewdidload i added 1 line and keep comment 1 line 
Added:     self.tokenView.direction=KSTokenViewScrollDirectionHorizontal;
Comment : [self.view addSubview:self.tokenView];
/* I commented the above line because i already gave as Class name  "KSTokenView" and  the outlet to token view in the storyboard. So i keep the Comment to the above line  */

2. keep Comment all the text in "performSearchWithString" method.

3.keep the static height in storyboard as 44.using constraint.

and Run the code you can see the problem what i faced.

**Comment by ajay2c9** [comment]
I have a small doubt in "Programmatically.swift" file .
 First i clear all the tokens and i added 3 tokens in the searchfield search by a letter. After adding that i search with 3 letters i kept the break point in "performSearchWithString"  delegate method. After clearing 1 by 1 letter, for last letter the clearing this delegate method is not called. How to identify the searching letter is empty or not.

**Comment by khawars** [comment]
Instead of adding height constraint, please use placeholder height in intrinsic content size, like in example projects. 
But I observed few bugs of autolayout with Xcode 8.0. Please use at least 8.1 or above. 
As far as I remember 'performSearchWithString' doesn't call when string length is 0. This was handled in v3. BTW, are you using latest version of KSTOKENVIEW?

**Comment by ajay2c9** [comment]
Hi,
I am using the latest Version. Please give suggestions for identifying for identifying the string length is 0. I need to add another functionality when search string length is 0.

Thank you

**Comment by ajay2c9** [comment]
i am adding the token to the tokenview like this with horizontal scrolling.

 [tokenView addTokenWithTitle:selectobj.usernameString  tokenObject:selectobj];

how to delete the sticky token. 
1.
KSToken*token=[[KSToken alloc] initWithTitle:selectobj.usernameString object:selectobj];
   [tokenView deleteToken:token];
2.
       [tokenView deleteTokenWithObject:selectobj];

i tried above two methods  few tokens are deleting for 2 method but few tokens are not deleted.

please give suggestions

**Comment by khawars** [comment]
I am not user of Instagram and not sure what it offers about this feature. But as per my understanding, you want to delete token if user select it? If yes, then you can just implement the delegate method when the token is selected and then call deleteToken method. Like this:

```
func tokenView(_ tokenView: KSTokenView, didSelectToken token: KSToken) {
        // Delete selected token
        tokenView.deleteToken(token)
}
```
