### ISSUE TITLE
tokens are not displaying

### ISSUE THREAD

**Issue by heatherSnepenger** [khawars/KSTokenView#72]
I'm on swift 2.3 and using version 2.5 of KSTokenView. The `addToken` method doesn't add tokens to the `KSTokenView` nor do the tokens get added when clicked from the `UITableView`. Doesn't seem like anyone else is reporting this issue?

**Comment by khawars** [comment]
@heatherSnepenger can you provide sample code how you are using it? You may look into "Programmatically" example. If you are still facing issue, you may re-open it.
