### ISSUE TITLE
[Question] How to enable editing of existing token?

### ISSUE THREAD

**Issue by ghost** [khawars/KSTokenView#73]
Once a user has created tokens, is there a way to enable editing of a created token?

E.g. if the user has created these tokens: **[Swift], [Visual Basic], [Objective C]** set, how can the change the token in place by:

1. tapping on the token, then
2. typing the new input e.g. [Swift language] (without deleting any tokens)

After the edit to the token, the resulting tokens will be **[Swift language], [Visual Basic], [Objective C]**

**Comment by khawars** [comment]
Currently, there is no way to edit a token. It can be deleted, but edited for now.
