### ISSUE TITLE
How to change color of indicator

### ISSUE THREAD

**Issue by pmbfish40** [khawars/KSTokenView#77]
I tried to to change indicator color but it didn't changed at all. The color is always blue

 tokenView.activityIndicatorColor = UIColor.red

![screenshot 2017-02-20 20 11 33](https://cloud.githubusercontent.com/assets/5268958/23133048/1d92eb08-f7a9-11e6-8390-06d81386ca24.png)

**Comment by khawars** [comment]
Check this:
http://stackoverflow.com/a/42436203/1444321

**Comment by khawars** [comment]
My bad, you are asking about Activity Indicator color not token background color. It should work, as you have tried.
Check Objective-c example in latest source code. I have tried changing color to red, and it does work.
Please let me know if issue is still there.
