### ISSUE TITLE
Cursor to go to New Line

### ISSUE THREAD

**Issue by basilmariano** [khawars/KSTokenView#78]
Can we make the Cursor go to **New Line** when typing if the text is already truncating?

<img width="316" alt="screen shot 2017-03-15 at 3 48 06 pm" src="https://cloud.githubusercontent.com/assets/5466582/23938331/dae33f56-0996-11e7-8d48-b679681dfe0d.png">

**Comment by khawars** [comment]
Nope. Currently this is not possible. Not sure if I would work on this feature in future.

**Comment by basilmariano** [comment]
That fine, i made it work already but not sure if i did it correctly though. Lol i did so many revisions, if you want i can give you the updated source and you cqn fix it up.
