### ISSUE TITLE
Tokens at top for first line

### ISSUE THREAD

**Issue by basilmariano** [khawars/KSTokenView#79]
Hi,

The tokens are automatically added top top.

<img width="322" alt="screen shot 2017-03-15 at 5 13 01 pm" src="https://cloud.githubusercontent.com/assets/5466582/23941176/cfe166e4-09a2-11e7-8040-71dd7034fd75.png">

I think it is better if the the first line will be at same Y position as the "To:" label until it reaches the second line,

**Comment by khawars** [comment]
@basilmariano as per current implementation, it starts from fixed Y position. Increasing number of lines will expand the view itself, but will not reposition Y. Currently, not getting enough time to implement this. You are free to submit pull request with this feature 👍
