### ISSUE TITLE
Crashing in iOS 10

### ISSUE THREAD

**Issue by mhegdeopteamix** [khawars/KSTokenView#81]
`      tokenView.promptText = "Top 5: "
        tokenView.placeholder = "Type to search"
        tokenView.descriptionText = "Languages"
        tokenView.maxTokenLimit = 5 //default is -1 for unlimited number of tokens
        tokenView.style = .squared`

I added token view in my tableview cell. the private property _tokenField is crashing if I add promptText, placeholder, description.

**Comment by khawars** [comment]
Please provide sample code, how are you using it.

**Comment by mhegdeopteamix** [comment]
@khawars  I already added sample code. I am using tokenView inside the tableviewCell.
