### ISSUE TITLE
Question: a way not to show the search?

### ISSUE THREAD

**Issue by igorkulman** [khawars/KSTokenView#82]
Is there a way not to show the search? I want to use it on top of my own table view.

**Comment by khawars** [comment]
I actually didn't get what you actually want to do. If you don't want to show search results, then why to use this control? Or you want to customize tableview UI?
However, to answer your question, there is no direct way as of now, to stop search result appearing. However, search results appears as soon as number of characters are equal value of ```minimumCharactersToSearch ``` property. You may set it to some large value, which you think user will not type, and it will not show.
