### ISSUE TITLE
kstokenview text comes empty

### ISSUE THREAD

**Issue by feliciaf** [khawars/KSTokenView#83]
Hi, when using the kstokenview, i have noticed that the tokenview.text = " " comes empty ? 
I need to grab the input of the user text, compare it with a textfield and add it to a database.

Please need help for any sugestions? if I need to use the kstokenfield so, i can grab the input of the user text?

**Comment by khawars** [comment]
At which event you are trying to get text? It should work. Could you please send some sample code?

BTW, you can also get the input string in following delegate method. Following is example:

```
func tokenView(_ token: KSTokenView, performSearchWithString string: String, completion: ((_ results: Array<AnyObject>) -> Void)?) {
        print(string)
}
```
You may re-open if there is still any issue.

**Comment by feliciaf** [comment]
@khawars  ... 
My goal: is once the user clicks on the object, it returns the object and take the string of that object and compare with other textfields.
My code: 
func tokenView(token: KSTokenView, performSearchWithString string: String, completion: ((results: Array<AnyObject>) -> Void)?) {
    
        let data = TranCodeSQL(objContext: self.managedObjectContext).Query("DELAY")
        
        var selectedArray = [[String: AnyObject]]()

                if ( data.count == 0 ){
                } else {
                    for i in 0..<data.count {
                        if (String(data[i]).lowercaseString.rangeOfString(string.lowercaseString) != nil) {
                                selectedArray.append(data[i])
                    
                        }
        
                    }
        
                }
        completion!(results: selectedArray)
    }
    
    
    func tokenView(token: KSTokenView, displayTitleForObject object: AnyObject) -> String {
 
        //returns values of ["desc"]
        return object["desc"] as! String
        
 
    }

**Comment by khawars** [comment]
But where are you checking ```tokenview.text```? I couldn't find it in above code.

**Comment by feliciaf** [comment]
where can I implement tokenview.text?

**Comment by feliciaf** [comment]
can i display two array titles,  and only return one array title?

**Comment by khawars** [comment]
You can implement ```tokenView.text``` anywhere you want. It will return any untokeznied text. 

Didn't get your second question regarding two array. Please explain.

**Comment by feliciaf** [comment]
ok for the first question. 
for the second question: 
Below, I am returning object["desc"] from the selectedArray. 
In func tokenView(token: KSTokenView, displayTitleForObject object: AnyObject) -> String {
    //returns values of ["desc"]
    return object["desc"] as! String 
}

But, I want to display 2 objects[["desc"]["sys_code"]]
and if i select a token, it returns object["sys_code"]

**Comment by feliciaf** [comment]
the first table cell: string A , string B
select table cell
and return string B

**Comment by feliciaf** [comment]
![screen shot 2017-07-06 at 10 13 13 am](https://user-images.githubusercontent.com/7524770/27915301-e0d8e780-6233-11e7-878a-a4e7fea6b577.png)
