### ISSUE TITLE
I am using KSTokenView, branch swift 2.3 Any guidance would be very helpful. This is for one UITextfield. I would like to use it for multiple textfields.How can I implement using this method? 

### ISSUE THREAD

**Issue by feliciaf** [khawars/KSTokenView#84]
//class VC
    class ViewController: UIViewController {    
     var arrayForDelayTypeTxtComboBox = [[String : AnyObject]]()
     var arrayForDelayCancellationTxtComboBox = [[String : AnyObject]]()
      
    override func viewDidLoad() {
            super.viewDidLoad()
            
    ksTokenView() 
    
    }
    //init tokenView
    func ksTokenView() {
            
            tokenView.delegate = self
            tokenView.promptText = " "
            tokenView.placeholder = "Search delay transcode"
            tokenView.descriptionText = "delay_system_code"
            tokenView.maxTokenLimit = 1
            tokenView.minimumCharactersToSearch = 0
            tokenView.style = .Squared
            tokenView.direction = .Vertical
    
     //added extension KSTokenViewDelegate
     extension ViewController: KSTokenViewDelegate {
         
      //func to search    
        func tokenView(token: KSTokenView, performSearchWithString string: String, completion: ((results: Array<AnyObject>) -> Void)?) {
                
                let data = arrayForDelayTypeTxtComboBox
                let dataTwo = arrayForDelayCancellationTxtComboBox
                
                var selectedArrayForDelayType = [[String: AnyObject]]()
                var selectedArrayForDelayCancellation = [[String: AnyObject]]()
                
                if (string.characters.isEmpty){
                    completion!(results: data)
                    return
                }
                for value in data {
                    if (String(value).lowercaseString.rangeOfString(string.lowercaseString) != nil) {
                        selectedArray.append(value) 
                    }
                }
                
                if (string.characters.isEmpty){
                    completion!(results: data)
                    return
                }
                
                completion!(results: selectedArray)
                print(string)
            }
            
        //display the title
              func tokenView(token: KSTokenView, displayTitleForObject object: AnyObject) -> String {
                let array1 = object["sytem_code"] as! String
                
                return array1
            }
            
       //add the tokens
         func tokenView(tokenView: KSTokenView, shouldAddToken token: KSToken) -> Bool {
               let saveString: String()
                saveString = token.title
                
                if token.title == ""  {
                    return false
                }
               
                return true
            }

**Comment by khawars** [comment]
Use it for multiple objects, just like you are using for one. However, in delegates of KSTokenView methods, you will receive reference of one user is interacting with. Just like ```tokenView``` in below method.
```func tokenView(tokenView: KSTokenView, shouldAddToken token: KSToken) -> Bool  {```
```// Check tokenView here and do your work```
```}```


You can check this reference and perform action accordingly.

**Comment by sagarsnehi** [comment]
I have used this as pod but whenever I am resignresponder for keyboard token view changes into text. please suggest on this.
