### ISSUE TITLE
Setting searchResultBackgroundColor does not seem to change the color

### ISSUE THREAD

**Issue by mjew** [khawars/KSTokenView#85]
I can set the tokenView.backgroundColor and it works.
When I set the tokenView.searchResultBackgroundColor it does not seem to affect the color of the search results table that appears.
Is there something else I need to do to affect the color of the search table's background?
- Matthew

**Comment by khawars** [comment]
You may have changed the background color correctly, but it is not visible because row colors are still default. Please try changing table row colors.
