### ISSUE TITLE
Possible bug in delegate function regarding hiding the search result

### ISSUE THREAD

**Issue by pk1** [khawars/KSTokenView#87]
Hi,

not sure if this has been already addressed but in case someone else is wondering what is going on here, I hope this will help.

The token view configuration has a property shouldHideSearchResultsOnSelect. If this is set to false, my understanding is that the currently shown search result should not disappear. But exactly this happens because the delegate function tokenFieldDidEndEditing in the class KSTokenView will always hide the search result without taking the above property into account.

So if you need to still show the result while a search result has been selected, just modify this delegate function:

`
if (shouldHideSearchResultsOnSelect) {
            _hideSearchResults()
}
`

@khawars : would be great if this could be fixed in one of the upcoming releases. Keep up the great work!

**Comment by khawars** [comment]
```shouldHideSearchResultsOnSelect``` means actually other way around. If set to ```true```, search results will hide once user selects an option from search results. If set to ```false```, search result will keep showing, and user can keep on selecting items.
Sorry for such late response.
You may reopen, if issue is still there.
