### ISSUE TITLE
swift 3.2 and 4.0 support

### ISSUE THREAD

**Issue by reshadf** [khawars/KSTokenView#88]
Hi Is there any support planned for the 3.2 and 4.0 swift versions?

**Comment by gabdsg** [comment]
Same here

**Comment by dlukianenko** [comment]
+1

**Comment by khawars** [comment]
Dears - Please try new commit for Swift 4 https://github.com/khawars/KSTokenView/commit/c4bc5386ae0d1f71c25e1770429064689120053b
