### ISSUE TITLE
Customize for KSTokenField

### ISSUE THREAD

**Issue by yunitaandini** [khawars/KSTokenView#89]
I define the tokenView height = 43, it works when token added.
But when all token deleted and I started to type custom string the height become little taller (but when back to its normal size when token added). I tried to customize your library, but I can't find which height should I custom.

Could you elaborate more about the height customization, please?

Your pod is really helpful, thank you.

**Comment by khawars** [comment]
Try to change height in Xib/Storyboard file of example project. It should be working fine.
Please reopen, if issue is still there.

<img width="250" alt="screen shot 2017-09-11 at 4 23 42 pm" src="https://user-images.githubusercontent.com/10417908/30274306-e6c8bef4-970d-11e7-9822-c1a685802d47.png">
