### ISSUE TITLE
Show all

### ISSUE THREAD

**Issue by cdf1982** [khawars/KSTokenView#9]
Good morning and thank you for your work, I just started looking at it but it looks exactly what I would have made myself, if I were able to... :)

This isn't actually an issue, more like a feature request... I see that the list of possible results is shown after at least 1 character is typed; I would love to show all possible results, let's say "unfiltered", when the user selects the view and hasn't typed anything yet.

I tried to set .minimumCharactersToSearch = 0, but it didn't work, I still need to type at least one character before search occurs.

There's a way to show every possible value right when editing begins?

**Comment by khawars** [comment]
Feature added in latest commit 7f6a3ed9e8e4c761a20545d993025edde9232962.
Just set ```minimumCharactersToSearch = 0```.
See example project ```AutolayoutExample```.
You can re-open if there is still any issue.
