### ISSUE TITLE
Custom TableViewCell

### ISSUE THREAD

**Issue by luongnhatlam** [khawars/KSTokenView#91]
Hello, I am working with my tableViewCell but when embed KSTokenView I have to use the default tableViewCell of it! How can I still use my tableViewCell or custom tableViewCell of KSTokenView???

**Comment by khawars** [comment]
You can still use your tableViewCell by implementing delegate method ```tokenView(_ tokenView: KSTokenView, withObject object: AnyObject, tableView: UITableView, cellForRowAtIndexPath indexPath: IndexPath) -> UITableViewCell```.

**Comment by luongnhatlam** [comment]
Thank you so much
