### ISSUE TITLE
TokenView too much after TokenLimit

### ISSUE THREAD

**Issue by LoopingLouieX** [khawars/KSTokenView#93]
If as example `tokenView.maxTokenLimit = 3` and there are already three tokens chosen from the list 
--> the tokenlist will be shown nevertheless and it is possible to choose a fourth token (this fourth token will be not in the list afterwards so that's correct)

**Suggestion:** If as example `tokenView.maxTokenLimit = 3` and the third token is chosen, the list will be not displayed anymore.

**Comment by khawars** [comment]
Done, in latest commit https://github.com/khawars/KSTokenView/commit/6a24f5c4f117fba12ef6c8b17ed80535ecb7fac5.
