### ISSUE TITLE
Case sensitive ?

### ISSUE THREAD

**Issue by Lecyp** [khawars/KSTokenView#94]
Hey !

First, tanks a lot for your great library 👍 

I just wanted to know if you were planing to define an option somewhere to render the searched text case sensitive and/or accent sensitive ?

Thank you very much for your feedback ;)

**Comment by khawars** [comment]
```KSTokenView``` doesn't actually perform search. It is a View, which provides delegate methods so that you may perform searches based on your requirement. You may use delegate methods like ```tokenView(_ tokenView: KSTokenView, performSearchWithString string: String, completion: ((Array<AnyObject>) -> Void)?)``` to customize your search results accordingly.
