### ISSUE TITLE
Text field color

### ISSUE THREAD

**Issue by RazvanCosmeanu** [khawars/KSTokenView#96]
Hello, and thank you for this library. I managed to customize everything how I want, but I have a question. Is it possible to change the text field color? If I set the tokenView.backgroundColor property to black, the text is not visible anymore as I write it. Thanks! Also tokenView.style = KSTokenViewStyle.squared doesn't work as intended, as I still get the rounded corners.

**Comment by khawars** [comment]
You can use ```tokenTextColor``` to set text color. Also setting style as ```squared``` works fine for me. 
Please check ```Programmatically``` working example for both of these issues.

**Comment by RazvanCosmeanu** [comment]
Thanks for the reply! I was talking about the UITextField textColor, not the token color, as stated in the title.

You are setting it as black in the _commonSetup() init function.
```
fileprivate func _commonSetup() {
      backgroundColor = UIColor.clear
      clipsToBounds = true
      _tokenField = KSTokenField(frame: CGRect(x: 0, y: 0, width: self.bounds.width, height: self.bounds.height))
      _tokenField.textColor = UIColor.black
     ............
}
```

But there is no get/set for it exposed in KSTokenView, and the _tokenField is private, so not customizable. Please mark it as an enhancement proposal, but I don't think it should be closed.
