### ISSUE TITLE
TokenTextField height is not updated

### ISSUE THREAD

**Issue by hannesoud** [khawars/KSTokenView#97]
TextField height is not updated when 
- Add 5 or 6 tokens
- Click done
- Focus textfield
- Remove all tokens

In this case, textfield height should be min value(line count 1), but it looks like multiline textfield.
http://prntscr.com/hn1zgl

it should be as following screenshot:
http://prntscr.com/hn1zsn

**Comment by khawars** [comment]
Hi @hannesoud 
I am trying to replicate the issue, but couldn't. Do you have the latest code?

**Comment by khawars** [comment]
Closing this as there is no more conversation on it. Please reopen, if issue is still there.
